baseurl = "https://shapescience.xyz/"
title = "Shapescience"

theme = "casper-two"
paginate = 10
footnoteReturnLinkContents = "↩"

languageCode = "en-us"
EnableEmoji = true
canonifyurls = true

googleAnalytics = "UA-42364112-9"

# http://themes.gohugo.io/casper/
# hugo new -t casper post/my-post.md

# https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences = true
pygmentsStyle = "monokai"
PygmentsCodeFences = true

DisqusShortname = "shapescience"

[permalinks]
  post = "/blog/:title/"
  page = "/:title/"

[taxonomies]
  category = "categories"
  author = "authors"
  tag = "tags"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  title = "Shapescience"
  subtitle = "Posts on algorithms, data science and software engineering. It's slowly taking shape!"
  description = "Arthur Flam's blog on algorithms, data science and software engineering. It's slowly taking shape!"
  metaDescription = ""
  Copyright = "All rights reserved - 2021"
  showSubscribe = true

  cover = "images/Black-Abstraction-Georgia-O-Keeffe.upscaled.jpg"
  shareimage = "images/shape-shapescience-okeefe.png"
  author = "shapescience"
  logo = "images/logo.white.svg"
  logodark = "images/logo.black.svg"
  # old syntax
  googleAnalyticsUserID = "UA-42364112-9"
  googleAnalytics = "UA-42364112-9"

  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  twitterName = "ArthurFlam"
  facebookName = "shapescience"
  # fbName = "shapescience"
  githubName = "arthur-flam"
  linkedinName = "ArthurFlam"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  showSupport = true
  mainSections = ["post"]


[[menu.main]]
name = "Home"
url = "https://shapescience.xyz"
weight = 0
#[[menu.main]]
#name = "Forum"
#url = "https://talk.shapescience.xyz"
#weight = -114


[related]
includeNewer = true
toLower = true
threshold=0

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "tags"
weight = 150
[[related.indices]]
name  = "author"
toLower = true
weight = 30
[[related.indices]]
name  = "tags"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"
